### ISSUE TITLE
bug: Internal Server Error

### ISSUE THREAD

**Issue by natterstefan** [Dean151/Aln-Symfony#17]
`https://api.feedmypet.app/user/reset` and some other endpoints respond with `"Internal Server Error"` at the moment.

### Example Request

```
POST https://api.feedmypet.app/user/reset
```

BODY
```
{
    "email": "<my email>"
}
```

**Comment by Dean151** [comment]
Should be fine right now. I've made some tests.

Please note that email sending is not 100% trusty. I've 10/10 on mail-tester.com ; but still some providers won't let my emails in.
I'll update that to an external smtp sometime in the future

**Comment by natterstefan** [comment]
Hey @Dean151,

I got the email, but this workflow (https://github.com/Dean151/Aln-Symfony#login-with-email-aka-for-password-reset) doesn't work. All I get is this:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/1043668/190873842-158b88ea-4376-4af2-877e-f5b9d9c6e34b.png">

**Comment by natterstefan** [comment]
It worked again after I reset my user, and it suddenly worked. 🤔 Can you see the internal server error in your logs?

But besides that, after associating my feeders, the API went down. 😬 .

**Comment by Dean151** [comment]
It's on me. I forgot to restart the websocket server after pulling my latest changes.
Should be fine now

**Comment by natterstefan** [comment]
No worries, @Dean151! Thank you very much!
