### ISSUE TITLE
Deployment Notes

### ISSUE THREAD

**Issue by natterstefan** [Dean151/Aln-Symfony#82]
Hi @Dean151.

How're you doing? I hope you are fine, and thanks again for setting up an open-source variant of the old API that powers pet feeders.

In the README, you added a `Deployment` section that is [currently WIP](https://github.com/Dean151/Aln-Symfony?tab=readme-ov-file#deployment). Do you already have any plans to elaborate on this section? I would be pleased about it, as I am trying to get more services into my internal network.

**Comment by Dean151** [comment]
Good news!
Took the time to clean-up things a bit, update Symfony to version 7, and document deployment!
https://github.com/Dean151/Aln-Symfony?tab=readme-ov-file#deploy-your-own-self-hosted-api

**Comment by natterstefan** [comment]
Hi @Dean151,

awesome! Thank you, great news. I plan to play around this or next week and (maybe) develop a docker image to make this easily deployable on e.g. a NAS or on Digital Ocean. I might have the time for it.

As this is not my usual stack, how are database migrations applied? Automatically on (re)start or is there anything one needs to execute/do?

**Comment by Dean151** [comment]
Oh, forgot about running migrations :D
It's `./bin/console doctrine:database:create` to create the empty DB
Then, `./bin/console doctrine:migration:migrate` to run the migrations. It'll create the tables
